# teacher / student promotion
promotion_gap:
  micro_f1: 0.015
  macro_f1: 0.015
promotion_patience: 2            # consecutive wins

# confidence curriculum
initial_confidence: 0.65   # start‑point
min_confidence:     0.35   # floor (don’t go lower)

# compute
gpus:
  label_gen: 1                   # use CUDA:1
  trainer:   0                   # use CUDA:0

# paths
root:           /mnt/raid/camie
teachers_dir:   ${root}/models/teachers
students_dir:   ${root}/models/students
datasets_dir:   ${root}/datasets
hf_token:       ${env:HF_TOKEN}
raw_data_root: /mnt/pool/booru